# Code generated by tools/contractsgen; DO NOT EDIT.
# Source: tools/contracts/manifest.json — per-line "validator-sidecar"/
# "validator-sidecar-ext" (2.2) + "data-hapi" sets, both + shared, at EVERY
# manifest line. Regenerate: go run ./tools/contractsgen -write
# Sourced by build.sh / verify.sh / manifest.sh. One pair of arrays per line
# (KITASSETS_VALIDATOR_IGS_<suffix> / KITASSETS_DATA_IGS_<suffix>, suffix =
# the line with "." stripped, e.g. "2.1" -> "21"); each row is
# "<key> <package-name> <version>" (space-separated, key first).

KITASSETS_LINES=(
  "2.0"
  "2.1"
  "2.2"
)

KITASSETS_VALIDATOR_IGS_20=(
  "uscore hl7.fhir.us.core 6.1.0"
  "crd hl7.fhir.us.davinci-crd 2.0.1"
  "dtr hl7.fhir.us.davinci-dtr 2.0.1"
  "pas hl7.fhir.us.davinci-pas 2.0.1"
  "pdex hl7.fhir.us.davinci-pdex 2.1.0"
  "sdc hl7.fhir.uv.sdc 3.0.0"
  "cdex hl7.fhir.us.davinci-cdex 2.1.0"
  "hrex hl7.fhir.us.davinci-hrex 1.1.0"
  "shnig shn.fhir.carry 1.0.0"
)

KITASSETS_DATA_IGS_20=(
  "uscore hl7.fhir.us.core 6.1.0"
  "cdex hl7.fhir.us.davinci-cdex 2.1.0"
  "hrex hl7.fhir.us.davinci-hrex 1.1.0"
  "pas hl7.fhir.us.davinci-pas 2.0.1"
)

KITASSETS_VALIDATOR_IGS_21=(
  "uscore hl7.fhir.us.core 7.0.0"
  "crd hl7.fhir.us.davinci-crd 2.1.0"
  "dtr hl7.fhir.us.davinci-dtr 2.1.0"
  "pas hl7.fhir.us.davinci-pas 2.1.0"
  "pdex hl7.fhir.us.davinci-pdex 2.1.0"
  "sdc hl7.fhir.uv.sdc 3.0.0"
  "cdex hl7.fhir.us.davinci-cdex 2.1.0"
  "hrex hl7.fhir.us.davinci-hrex 1.1.0"
  "shnig shn.fhir.carry 1.0.0"
)

KITASSETS_DATA_IGS_21=(
  "uscore hl7.fhir.us.core 7.0.0"
  "cdex hl7.fhir.us.davinci-cdex 2.1.0"
  "hrex hl7.fhir.us.davinci-hrex 1.1.0"
  "pas hl7.fhir.us.davinci-pas 2.1.0"
)

KITASSETS_VALIDATOR_IGS_22=(
  "uscore hl7.fhir.us.core 7.0.0"
  "crd hl7.fhir.us.davinci-crd 2.2.1"
  "dtr hl7.fhir.us.davinci-dtr 2.2.0"
  "pas hl7.fhir.us.davinci-pas 2.2.1"
  "pdex hl7.fhir.us.davinci-pdex 2.1.0"
  "sdc hl7.fhir.uv.sdc 4.0.0"
  "cdex hl7.fhir.us.davinci-cdex 2.1.0"
  "hrex hl7.fhir.us.davinci-hrex 1.2.0"
  "extensions hl7.fhir.uv.extensions.r4 5.3.0-ballot-tc1"
  "shnig shn.fhir.carry 1.0.0"
)

KITASSETS_DATA_IGS_22=(
  "uscore hl7.fhir.us.core 7.0.0"
  "cdex hl7.fhir.us.davinci-cdex 2.1.0"
  "hrex hl7.fhir.us.davinci-hrex 1.2.0"
  "pas hl7.fhir.us.davinci-pas 2.2.1"
)
