#!/usr/bin/env bash
#
# tools/kitassets/modules.sh — derive the single-JRE module union.
#
# Runs jdeps over BOTH exploded WARs (HAPI validator/data server are the same
# artifact; br-provider is the second), unions the two module lists, appends the
# curated always-set, and writes tools/kitassets/modules.txt (committed). jdeps
# output is ADVISORY — the executable proof is verify.sh booting all three
# children on the freshly linked JRE.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
DIST="${KIT_ASSETS_DIST:-$REPO/dist/kitassets}"
OUT="$REPO/tools/kitassets/modules.txt"

java_home() {
  if [ -n "${JAVA_HOME:-}" ] && [ -x "$JAVA_HOME/bin/jdeps" ]; then echo "$JAVA_HOME"; return; fi
  if [ "$(uname)" = Darwin ]; then /usr/libexec/java_home -v 21; return; fi
  echo "JAVA_HOME with a JDK 21 (jdeps) required" >&2; exit 1
}
JDEPS="$(java_home)/bin/jdeps"
"$JDEPS" --version 2>/dev/null | grep -q '^21' \
  || { echo "[modules] FAIL: jdeps 21 required, got: $("$JDEPS" --version 2>&1 | head -1)" >&2; exit 1; }

[ -f "$DIST/hapi/main.war" ] && [ -f "$DIST/brprovider/main.war" ] \
  || { echo "WARs missing under $DIST — run tools/kitassets/build.sh first" >&2; exit 1; }

mods_for() { # mods_for <war> -> comma-separated module list on stdout
  # The libs ride --class-path (classpath mode), NOT as jdeps roots: several
  # WEB-INF/lib jars ship module-info descriptors whose requires-graph doesn't
  # resolve (hibernate-search → org.hibernate.orm.core), and jdeps aborts
  # building a module config from them. Classpath mode sidesteps resolution;
  # -R still walks the transitive closure for --print-module-deps.
  local war="$1" tmp out
  tmp=$(mktemp -d)
  ( cd "$tmp" && unzip -qq "$war" 'WEB-INF/*' )
  out=$("$JDEPS" --multi-release 21 --print-module-deps --ignore-missing-deps -q -R \
    --class-path "$tmp/WEB-INF/lib/*" "$tmp/WEB-INF/classes") \
    || { echo "[modules] FAIL: jdeps errored for $war" >&2; rm -rf "$tmp"; return 1; }
  rm -rf "$tmp"
  [ -n "$out" ] || { echo "[modules] FAIL: jdeps produced no module list for $war" >&2; return 1; }
  echo "$out"
}

echo "[modules] jdeps over hapi/main.war ..." >&2
HAPI_MODS="$(mods_for "$DIST/hapi/main.war")"
echo "[modules] jdeps over brprovider/main.war ..." >&2
BRP_MODS="$(mods_for "$DIST/brprovider/main.war")"

# Curated always-set: TLS EC suites + PKCS#11 (jdk.crypto.*), zip filesystem
# (Spring Boot nested-jar access), jdk.unsupported (Unsafe — netty/hibernate).
ALWAYS="jdk.crypto.ec,jdk.crypto.cryptoki,jdk.zipfs,jdk.unsupported"

{
  echo "# jlink module union — GENERATED by tools/kitassets/modules.sh; do not hand-edit."
  echo "# Derivation: jdeps --multi-release 21 --print-module-deps --ignore-missing-deps -q -R --class-path <WEB-INF/lib/*> <WEB-INF/classes>"
  echo "#   over hapiproject/hapi@sha256:1be4d7ff… main.war  ∪  br-provider:43a4806 main.war"
  echo "#   + curated always-set: $ALWAYS"
  echo "# Date: $(date -u +%Y-%m-%d) — advisory only; the executable proof is tools/kitassets/verify.sh."
  printf '%s\n%s\n%s\n' "$HAPI_MODS" "$BRP_MODS" "$ALWAYS" | tr ',' '\n' | sed '/^$/d' | sort -u
} > "$OUT"
echo "[modules] wrote $OUT ($(grep -cv '^#' "$OUT") modules)"
