// Code generated by tools/contractsgen; DO NOT EDIT.
// Source: tools/contracts/manifest.json — kitdIGPinsValidator resolves
// "validator-sidecar" (2.0/2.1) or "validator-sidecar-ext" (2.2, the
// extensions-closure superset) per line;
// kitdIGPinsData resolves "data-hapi" per line. Both + shared, at EVERY
// manifest line (kit/kitd/stack.go's Line/AdditionalValidatorLines pick
// which ones javachildren.go's BuildValidatorChildSpec actually boots).
// Regenerate: go run ./tools/contractsgen -write

package kitd

// kitdIGPinsValidator returns the validator's IG pin set for line; an
// unrecognized line returns nil.
func kitdIGPinsValidator(line string) []ig {
	switch line {
	case "2.0":
		return []ig{
			{"uscore", "igs-validator", "hl7.fhir.us.core", "6.1.0"},
			{"crd", "igs-validator", "hl7.fhir.us.davinci-crd", "2.0.1"},
			{"dtr", "igs-validator", "hl7.fhir.us.davinci-dtr", "2.0.1"},
			{"pas", "igs-validator", "hl7.fhir.us.davinci-pas", "2.0.1"},
			{"pdex", "igs-validator", "hl7.fhir.us.davinci-pdex", "2.1.0"},
			{"sdc", "igs-validator", "hl7.fhir.uv.sdc", "3.0.0"},
			{"cdex", "igs-validator", "hl7.fhir.us.davinci-cdex", "2.1.0"},
			{"hrex", "igs-validator", "hl7.fhir.us.davinci-hrex", "1.1.0"},
			{"shnig", "igs-validator", "shn.fhir.carry", "1.0.0"},
		}
	case "2.1":
		return []ig{
			{"uscore", "igs-validator", "hl7.fhir.us.core", "7.0.0"},
			{"crd", "igs-validator", "hl7.fhir.us.davinci-crd", "2.1.0"},
			{"dtr", "igs-validator", "hl7.fhir.us.davinci-dtr", "2.1.0"},
			{"pas", "igs-validator", "hl7.fhir.us.davinci-pas", "2.1.0"},
			{"pdex", "igs-validator", "hl7.fhir.us.davinci-pdex", "2.1.0"},
			{"sdc", "igs-validator", "hl7.fhir.uv.sdc", "3.0.0"},
			{"cdex", "igs-validator", "hl7.fhir.us.davinci-cdex", "2.1.0"},
			{"hrex", "igs-validator", "hl7.fhir.us.davinci-hrex", "1.1.0"},
			{"shnig", "igs-validator", "shn.fhir.carry", "1.0.0"},
		}
	case "2.2":
		return []ig{
			{"uscore", "igs-validator", "hl7.fhir.us.core", "7.0.0"},
			{"crd", "igs-validator", "hl7.fhir.us.davinci-crd", "2.2.1"},
			{"dtr", "igs-validator", "hl7.fhir.us.davinci-dtr", "2.2.0"},
			{"pas", "igs-validator", "hl7.fhir.us.davinci-pas", "2.2.1"},
			{"pdex", "igs-validator", "hl7.fhir.us.davinci-pdex", "2.1.0"},
			{"sdc", "igs-validator", "hl7.fhir.uv.sdc", "4.0.0"},
			{"cdex", "igs-validator", "hl7.fhir.us.davinci-cdex", "2.1.0"},
			{"hrex", "igs-validator", "hl7.fhir.us.davinci-hrex", "1.2.0"},
			{"extensions", "igs-validator", "hl7.fhir.uv.extensions.r4", "5.3.0-ballot-tc1"},
			{"shnig", "igs-validator", "shn.fhir.carry", "1.0.0"},
		}
	default:
		return nil
	}
}

// kitdIGPinsData returns the data server's IG pin set for line; an
// unrecognized line returns nil.
func kitdIGPinsData(line string) []ig {
	switch line {
	case "2.0":
		return []ig{
			{"uscore", "igs-data", "hl7.fhir.us.core", "6.1.0"},
			{"cdex", "igs-data", "hl7.fhir.us.davinci-cdex", "2.1.0"},
			{"hrex", "igs-data", "hl7.fhir.us.davinci-hrex", "1.1.0"},
			{"pas", "igs-data", "hl7.fhir.us.davinci-pas", "2.0.1"},
		}
	case "2.1":
		return []ig{
			{"uscore", "igs-data", "hl7.fhir.us.core", "7.0.0"},
			{"cdex", "igs-data", "hl7.fhir.us.davinci-cdex", "2.1.0"},
			{"hrex", "igs-data", "hl7.fhir.us.davinci-hrex", "1.1.0"},
			{"pas", "igs-data", "hl7.fhir.us.davinci-pas", "2.1.0"},
		}
	case "2.2":
		return []ig{
			{"uscore", "igs-data", "hl7.fhir.us.core", "7.0.0"},
			{"cdex", "igs-data", "hl7.fhir.us.davinci-cdex", "2.1.0"},
			{"hrex", "igs-data", "hl7.fhir.us.davinci-hrex", "1.2.0"},
			{"pas", "igs-data", "hl7.fhir.us.davinci-pas", "2.2.1"},
		}
	default:
		return nil
	}
}
